package ca.uhn.fhir.jpa.starter.cohort.service.r5;

import ca.uhn.fhir.rest.server.exceptions.ResourceNotFoundException;
import org.hl7.fhir.r5.model.*;
import org.opencds.cqf.fhir.api.Repository;
import org.opencds.cqf.fhir.utility.search.Searches;

import java.util.Objects;

public class CohorteService {

	private final Repository repository;
	private final CohorteEvaluationOptions settings;

	public CohorteService(Repository repository, CohorteEvaluationOptions settings) {
		this.settings = settings;
		this.repository = Objects.requireNonNull(repository);
	}

	/**
	 * Performs the cohorting operation
	 *
	 * @param researchStudyUrl      The canonical URL of the {@link ResearchStudy} used as the cohorting basis.
	 * @param researchStudyEndpoint The endpoint that contains the {@link ResearchStudy} and associated resources.
	 * @param dataEndpoint          The endpoint providing access to the referenced data.
	 * @param terminologyEndpoint   The endpoint providing access to terminology (if applicable).
	 * @return A {@link Group} representing the eligible patient cohort.
	 * @throws ResourceNotFoundException if the {@link ResearchStudy} cannot be found.
	 */
	public Group cohorting(
		CanonicalType researchStudyUrl,
		Endpoint researchStudyEndpoint,
		Endpoint dataEndpoint,
		Endpoint terminologyEndpoint) {
		Repository repo = Repositories.proxy(repository, false, dataEndpoint, researchStudyEndpoint, terminologyEndpoint);
		Bundle b = repo.search(Bundle.class, ResearchStudy.class, Searches.byCanonical(researchStudyUrl.getCanonical()), null);
		if (b.getEntry().isEmpty()) {
			var errorMsg = String.format("Unable to find ResearchStudy with url: %s", researchStudyUrl.getCanonical());
			throw new ResourceNotFoundException(errorMsg);
		}
		ResearchStudy researchStudy = (ResearchStudy) b.getEntry().get(0).getResource();
		CohorteProcessor cohorteProcessor = new CohorteProcessor(repo, settings, new RepositorySubjectProvider());
		Group group = cohorteProcessor.cohorting(researchStudy);
		buildAndSaveGroup(repo, group, researchStudy);
		updateResearchStudyWithGroup(repo, researchStudy, group);
		return group;
	}

	/**
	 * Updates the given {@link ResearchStudy} with a reference to the given {@link Group} and update the study phase.
	 *
	 * @param repo           The repository used for updates.
	 * @param researchStudy  The {@link ResearchStudy} to be updated.
	 * @param group          The {@link Group} generated by the cohorting process.
	 */
	public void updateResearchStudyWithGroup(Repository repo, ResearchStudy researchStudy, Group group) {
		researchStudy.getRecruitment().setActualGroup(new Reference(group));
		CodeableConcept phase = new CodeableConcept();
		phase.addCoding()
			.setCode("post-cohorting")
			.setSystem("https://www.centreantoinelacassagne.org/CodeSystem/COS-CustomStudyPhases");
		researchStudy.setPhase(phase);

		repo.update(researchStudy);
	}

	/**
	 * Builds the {@link Group} properties based on the given {@link ResearchStudy} information and saves it via the repository.
	 *
	 * @param repo           The repository used to save the {@link Group}.
	 * @param group          The {@link Group} instance to build and update.
	 * @param researchStudy  The {@link ResearchStudy} used as reference for group attributes.
	 */
	public void buildAndSaveGroup(Repository repo, Group group, ResearchStudy researchStudy) {
		group.setId("group" + "-" + researchStudy.getIdElement().getIdPart());
		group.setType(Group.GroupType.PERSON);
		group.setMembership(Group.GroupMembershipBasis.ENUMERATED);
		group.setActive(true);
		group.setDescription(researchStudy.getDescription());
		group.setName("Patient Eligible for: " + researchStudy.getName());
		repo.update(group);
	}
}
